name: Create PR from Develop to Main

on:
  workflow_run:
    workflows: ["CI Build & Test"]
    types:
      - completed
    branches:
      - develop

jobs:
  create-pull-request:
    # Esta condição garante que o job só execute se o workflow anterior foi bem-sucedido
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Necessário para a ação de checkout (actions/checkout)
      pull-requests: write   # Necessário para criar o Pull Request (gh pr create)

    steps:
      # Passo 1: Faz o checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Cria o Pull Request
      - name: Create Pull Request if one does not exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh pr list --head develop --base main --state open | grep -q "develop"; then
            echo "Workflow de CI/CD concluído com sucesso. Criando um novo Pull Request..."
            gh pr create \
              --base main \
              --head develop \
              --title 'feat: Sincronizar develop com main' \
              --body 'Este PR foi criado automaticamente após o sucesso do workflow de CI/CD para sincronizar as mudanças da branch `develop` com a `main`. Por favor, revise, aprove e faça o merge.'
          else
            echo "Um Pull Request da branch develop para a main já existe."
          fi