# .github/workflows/terraform-deploy.yml

name: 'Terraform Deploy PROD'

on:
  push:
    branches:
      - main # Dispara SOMENTE em push para a branch main

jobs:
  deploy-prod:
    name: 'Deploy Infra to Produção'
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: 
      name: producao # Aponta para o Environment do GitHub
      url: 'http://sojoga.com.br' # Opcional: URL do ambiente de produção

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PROD}}
          aws-region: sa-east-1 # Alinhando com a região do deploy da app

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Workspace'
        run: terraform workspace select prod || terraform workspace new prod

      - name: 'Import DynamoDB Table'
        run: terraform import aws_dynamodb_table.user_table Usuario-prod || true

      - name: 'Import ECR Repository'
        run: terraform import aws_ecr_repository.sojoga_backend_repo sojoga-backend-prod || true

      - name: 'Import IAM Role'
        run: terraform import aws_iam_role.ecs_task_execution_role ecs-task-execution-role-prod || true

      - name: 'Import Internet Gateway'
        run: terraform import aws_internet_gateway.gw igw-0b9a57d3570e0eb60 || true

      - name: 'Import Target Group'
        continue-on-error: true
        run: |
          TG_ARN=$(aws elbv2 describe-target-groups --names tg-sojoga-br-prod --region sa-east-1 --query "TargetGroups[0].TargetGroupArn" --output text | tr -d '\r')
          if [ -n "$TG_ARN" ] && [ "$TG_ARN" != "None" ]; then
            echo "Importing Target Group: $TG_ARN"
            terraform import aws_lb_target_group.main "$TG_ARN"
          else
            echo "Target Group 'tg-sojoga-br-prod' not found, skipping import."
          fi

      - name: 'Terraform Plan'
        run: terraform plan -var="environment=prod" -var="jwt_secret_arn=${{ secrets.JWT_SECRET_ARN }}" -out=tfplan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan
